-simple page not found, add routes
billenniumJavaLodz/quiz-app-frontend pull request #7
Opened 2020-04-08 13:34 UTC by SzymonKajdan

2020-04-08 13:40 UTC, PiotrLawniczek requested changes

2020-04-08 13:40 UTC, PiotrLawniczek commented on src/app/service/user.service.ts
> +    return this.httpClient.get<UserModel>(this.url + '/id');
Przekazujesz sobie id z url w home-page.component.ts a tutaj statycznie podajesz `'/id'` a parametru metody nie używasz nigdzie

2020-04-08 13:40 UTC, PiotrLawniczek commented on src/app/service/user.service.ts
> +  url = "http://localhost:8080/user";
url podstawowy `http://localhost:8080/` powinien znajdować się w pliku environment i tutaj tylko odczytywany.

2020-04-09 06:16 UTC, SzymonKajdan commented on src/app/service/user.service.ts
> +  url = "http://localhost:8080/user";
porpawione

2020-04-09 06:17 UTC, SzymonKajdan commented on src/app/service/user.service.ts
> +    return this.httpClient.get<UserModel>(this.url + '/id');
poprawione

2020-04-09 06:18 UTC, SzymonKajdan commented on src/app/service/user.service.ts
> +    return this.httpClient.get<UserModel>(environment.baseUrl + this.userUrl + userId);
Tak mysle czy nie powinnismy oblugiwac bledu w chwili gdy coś poleci nie tak ?

2020-04-09 07:20 UTC, PiotrLawniczek commented on src/app/service/user.service.ts
> +    return this.httpClient.get<UserModel>(environment.baseUrl + this.userUrl + userId);
takie obsługi robi sie w hhtp interceptorze :) może później

2020-04-09 07:21 UTC, PiotrLawniczek approved these changes

2020-04-09 07:30 UTC, merged